export const LAMBDA_POST_ACTIONS = {
  CREATE_PET: "CREATE_PET",
  EDIT_PET: "EDIT_PET",
  GET_PET: "GET_PET",
  GET_MY_PETS: "GET_MY_PETS",
  CREATE_DOC: "CREATE_DOC",
  GET_PET_DOCS: "GET_PET_DOCS",
  CREATE_DOC_TYPE: "CREATE_DOC_TYPE",
};
