export const NAVIGATION_CONTAINERS = {
  HOME: 'HOME',
  GET_STARTED: 'GET_STARTED',
  MY_PETS: 'MY_PETS',
  EDIT_PET: 'EDIT_PET',
  PET_DOCS: 'PET_DOCS',
  ADD_DOC: 'ADD_DOC',
  ADD_DOC_TYPE: 'ADD_DOC_TYPE',
};
